# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: i_common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import i_onnx_common_pb2 as i__onnx__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='i_common.proto',
  package='aihwx.inferencing',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ei_common.proto\x12\x11\x61ihwx.inferencing\x1a\x13i_onnx_common.proto\"R\n\x0eOptimizerProto\x12\n\n\x02id\x18\x01 \x02(\t\x12\x34\n\targuments\x18\x02 \x03(\x0b\x32!.aihwx.inferencing.AttributeProto\"R\n\x0ePrimitiveProto\x12\n\n\x02id\x18\x01 \x02(\t\x12\x34\n\targuments\x18\x02 \x03(\x0b\x32!.aihwx.inferencing.AttributeProto\"R\n\x0eTransformProto\x12\n\n\x02id\x18\x01 \x02(\t\x12\x34\n\targuments\x18\x02 \x03(\x0b\x32!.aihwx.inferencing.AttributeProto\"\x85\x01\n\nLayerProto\x12\n\n\x02id\x18\x01 \x02(\t\x12\x34\n\targuments\x18\x02 \x03(\x0b\x32!.aihwx.inferencing.AttributeProto\x12\x35\n\nstate_dict\x18\x03 \x03(\x0b\x32!.aihwx.inferencing.AttributeProto\"[\n\x17\x41\x63tivationFunctionProto\x12\n\n\x02id\x18\x01 \x02(\t\x12\x34\n\targuments\x18\x02 \x03(\x0b\x32!.aihwx.inferencing.AttributeProto\"\x9e\x01\n\x19LayerOrActivationFunction\x12I\n\x13\x61\x63tivation_function\x18\x01 \x01(\x0b\x32*.aihwx.inferencing.ActivationFunctionProtoH\x00\x12.\n\x05layer\x18\x02 \x01(\x0b\x32\x1d.aihwx.inferencing.LayerProtoH\x00\x42\x06\n\x04item\"R\n\x0eSchedulerProto\x12\n\n\x02id\x18\x01 \x02(\t\x12\x34\n\targuments\x18\x02 \x03(\x0b\x32!.aihwx.inferencing.AttributeProto\"U\n\x11LossFunctionProto\x12\n\n\x02id\x18\x01 \x02(\t\x12\x34\n\targuments\x18\x02 \x03(\x0b\x32!.aihwx.inferencing.AttributeProto\"c\n\x07Network\x12\x1a\n\x12weight_template_id\x18\x01 \x02(\t\x12<\n\x06layers\x18\x02 \x03(\x0b\x32,.aihwx.inferencing.LayerOrActivationFunction\"(\n\x07Version\x12\x0e\n\x06schema\x18\x01 \x02(\x03\x12\r\n\x05opset\x18\x02 \x02(\x03'
  ,
  dependencies=[i__onnx__common__pb2.DESCRIPTOR,])




_OPTIMIZERPROTO = _descriptor.Descriptor(
  name='OptimizerProto',
  full_name='aihwx.inferencing.OptimizerProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='aihwx.inferencing.OptimizerProto.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='aihwx.inferencing.OptimizerProto.arguments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=140,
)


_PRIMITIVEPROTO = _descriptor.Descriptor(
  name='PrimitiveProto',
  full_name='aihwx.inferencing.PrimitiveProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='aihwx.inferencing.PrimitiveProto.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='aihwx.inferencing.PrimitiveProto.arguments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=224,
)


_TRANSFORMPROTO = _descriptor.Descriptor(
  name='TransformProto',
  full_name='aihwx.inferencing.TransformProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='aihwx.inferencing.TransformProto.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='aihwx.inferencing.TransformProto.arguments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=308,
)


_LAYERPROTO = _descriptor.Descriptor(
  name='LayerProto',
  full_name='aihwx.inferencing.LayerProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='aihwx.inferencing.LayerProto.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='aihwx.inferencing.LayerProto.arguments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state_dict', full_name='aihwx.inferencing.LayerProto.state_dict', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=444,
)


_ACTIVATIONFUNCTIONPROTO = _descriptor.Descriptor(
  name='ActivationFunctionProto',
  full_name='aihwx.inferencing.ActivationFunctionProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='aihwx.inferencing.ActivationFunctionProto.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='aihwx.inferencing.ActivationFunctionProto.arguments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=537,
)


_LAYERORACTIVATIONFUNCTION = _descriptor.Descriptor(
  name='LayerOrActivationFunction',
  full_name='aihwx.inferencing.LayerOrActivationFunction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='activation_function', full_name='aihwx.inferencing.LayerOrActivationFunction.activation_function', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='layer', full_name='aihwx.inferencing.LayerOrActivationFunction.layer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='item', full_name='aihwx.inferencing.LayerOrActivationFunction.item',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=540,
  serialized_end=698,
)


_SCHEDULERPROTO = _descriptor.Descriptor(
  name='SchedulerProto',
  full_name='aihwx.inferencing.SchedulerProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='aihwx.inferencing.SchedulerProto.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='aihwx.inferencing.SchedulerProto.arguments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=700,
  serialized_end=782,
)


_LOSSFUNCTIONPROTO = _descriptor.Descriptor(
  name='LossFunctionProto',
  full_name='aihwx.inferencing.LossFunctionProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='aihwx.inferencing.LossFunctionProto.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='aihwx.inferencing.LossFunctionProto.arguments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=784,
  serialized_end=869,
)


_NETWORK = _descriptor.Descriptor(
  name='Network',
  full_name='aihwx.inferencing.Network',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight_template_id', full_name='aihwx.inferencing.Network.weight_template_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='layers', full_name='aihwx.inferencing.Network.layers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=871,
  serialized_end=970,
)


_VERSION = _descriptor.Descriptor(
  name='Version',
  full_name='aihwx.inferencing.Version',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='schema', full_name='aihwx.inferencing.Version.schema', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opset', full_name='aihwx.inferencing.Version.opset', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=972,
  serialized_end=1012,
)

_OPTIMIZERPROTO.fields_by_name['arguments'].message_type = i__onnx__common__pb2._ATTRIBUTEPROTO
_PRIMITIVEPROTO.fields_by_name['arguments'].message_type = i__onnx__common__pb2._ATTRIBUTEPROTO
_TRANSFORMPROTO.fields_by_name['arguments'].message_type = i__onnx__common__pb2._ATTRIBUTEPROTO
_LAYERPROTO.fields_by_name['arguments'].message_type = i__onnx__common__pb2._ATTRIBUTEPROTO
_LAYERPROTO.fields_by_name['state_dict'].message_type = i__onnx__common__pb2._ATTRIBUTEPROTO
_ACTIVATIONFUNCTIONPROTO.fields_by_name['arguments'].message_type = i__onnx__common__pb2._ATTRIBUTEPROTO
_LAYERORACTIVATIONFUNCTION.fields_by_name['activation_function'].message_type = _ACTIVATIONFUNCTIONPROTO
_LAYERORACTIVATIONFUNCTION.fields_by_name['layer'].message_type = _LAYERPROTO
_LAYERORACTIVATIONFUNCTION.oneofs_by_name['item'].fields.append(
  _LAYERORACTIVATIONFUNCTION.fields_by_name['activation_function'])
_LAYERORACTIVATIONFUNCTION.fields_by_name['activation_function'].containing_oneof = _LAYERORACTIVATIONFUNCTION.oneofs_by_name['item']
_LAYERORACTIVATIONFUNCTION.oneofs_by_name['item'].fields.append(
  _LAYERORACTIVATIONFUNCTION.fields_by_name['layer'])
_LAYERORACTIVATIONFUNCTION.fields_by_name['layer'].containing_oneof = _LAYERORACTIVATIONFUNCTION.oneofs_by_name['item']
_SCHEDULERPROTO.fields_by_name['arguments'].message_type = i__onnx__common__pb2._ATTRIBUTEPROTO
_LOSSFUNCTIONPROTO.fields_by_name['arguments'].message_type = i__onnx__common__pb2._ATTRIBUTEPROTO
_NETWORK.fields_by_name['layers'].message_type = _LAYERORACTIVATIONFUNCTION
DESCRIPTOR.message_types_by_name['OptimizerProto'] = _OPTIMIZERPROTO
DESCRIPTOR.message_types_by_name['PrimitiveProto'] = _PRIMITIVEPROTO
DESCRIPTOR.message_types_by_name['TransformProto'] = _TRANSFORMPROTO
DESCRIPTOR.message_types_by_name['LayerProto'] = _LAYERPROTO
DESCRIPTOR.message_types_by_name['ActivationFunctionProto'] = _ACTIVATIONFUNCTIONPROTO
DESCRIPTOR.message_types_by_name['LayerOrActivationFunction'] = _LAYERORACTIVATIONFUNCTION
DESCRIPTOR.message_types_by_name['SchedulerProto'] = _SCHEDULERPROTO
DESCRIPTOR.message_types_by_name['LossFunctionProto'] = _LOSSFUNCTIONPROTO
DESCRIPTOR.message_types_by_name['Network'] = _NETWORK
DESCRIPTOR.message_types_by_name['Version'] = _VERSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OptimizerProto = _reflection.GeneratedProtocolMessageType('OptimizerProto', (_message.Message,), {
  'DESCRIPTOR' : _OPTIMIZERPROTO,
  '__module__' : 'i_common_pb2'
  # @@protoc_insertion_point(class_scope:aihwx.inferencing.OptimizerProto)
  })
_sym_db.RegisterMessage(OptimizerProto)

PrimitiveProto = _reflection.GeneratedProtocolMessageType('PrimitiveProto', (_message.Message,), {
  'DESCRIPTOR' : _PRIMITIVEPROTO,
  '__module__' : 'i_common_pb2'
  # @@protoc_insertion_point(class_scope:aihwx.inferencing.PrimitiveProto)
  })
_sym_db.RegisterMessage(PrimitiveProto)

TransformProto = _reflection.GeneratedProtocolMessageType('TransformProto', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFORMPROTO,
  '__module__' : 'i_common_pb2'
  # @@protoc_insertion_point(class_scope:aihwx.inferencing.TransformProto)
  })
_sym_db.RegisterMessage(TransformProto)

LayerProto = _reflection.GeneratedProtocolMessageType('LayerProto', (_message.Message,), {
  'DESCRIPTOR' : _LAYERPROTO,
  '__module__' : 'i_common_pb2'
  # @@protoc_insertion_point(class_scope:aihwx.inferencing.LayerProto)
  })
_sym_db.RegisterMessage(LayerProto)

ActivationFunctionProto = _reflection.GeneratedProtocolMessageType('ActivationFunctionProto', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVATIONFUNCTIONPROTO,
  '__module__' : 'i_common_pb2'
  # @@protoc_insertion_point(class_scope:aihwx.inferencing.ActivationFunctionProto)
  })
_sym_db.RegisterMessage(ActivationFunctionProto)

LayerOrActivationFunction = _reflection.GeneratedProtocolMessageType('LayerOrActivationFunction', (_message.Message,), {
  'DESCRIPTOR' : _LAYERORACTIVATIONFUNCTION,
  '__module__' : 'i_common_pb2'
  # @@protoc_insertion_point(class_scope:aihwx.inferencing.LayerOrActivationFunction)
  })
_sym_db.RegisterMessage(LayerOrActivationFunction)

SchedulerProto = _reflection.GeneratedProtocolMessageType('SchedulerProto', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULERPROTO,
  '__module__' : 'i_common_pb2'
  # @@protoc_insertion_point(class_scope:aihwx.inferencing.SchedulerProto)
  })
_sym_db.RegisterMessage(SchedulerProto)

LossFunctionProto = _reflection.GeneratedProtocolMessageType('LossFunctionProto', (_message.Message,), {
  'DESCRIPTOR' : _LOSSFUNCTIONPROTO,
  '__module__' : 'i_common_pb2'
  # @@protoc_insertion_point(class_scope:aihwx.inferencing.LossFunctionProto)
  })
_sym_db.RegisterMessage(LossFunctionProto)

Network = _reflection.GeneratedProtocolMessageType('Network', (_message.Message,), {
  'DESCRIPTOR' : _NETWORK,
  '__module__' : 'i_common_pb2'
  # @@protoc_insertion_point(class_scope:aihwx.inferencing.Network)
  })
_sym_db.RegisterMessage(Network)

Version = _reflection.GeneratedProtocolMessageType('Version', (_message.Message,), {
  'DESCRIPTOR' : _VERSION,
  '__module__' : 'i_common_pb2'
  # @@protoc_insertion_point(class_scope:aihwx.inferencing.Version)
  })
_sym_db.RegisterMessage(Version)


# @@protoc_insertion_point(module_scope)
