# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: i_onnx_common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13i_onnx_common.proto\x12\x11\x61ihwx.inferencing"\xb5\x03\n\x0e\x41ttributeProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12=\n\x04type\x18\x14 \x01(\x0e\x32/.aihwx.inferencing.AttributeProto.AttributeType\x12\t\n\x01\x66\x18\x02 \x01(\x02\x12\t\n\x01i\x18\x03 \x01(\x03\x12\t\n\x01s\x18\x04 \x01(\x0c\x12)\n\x01t\x18\x05 \x01(\x0b\x32\x1e.aihwx.inferencing.TensorProto\x12\t\n\x01\x62\x18\x65 \x01(\x08\x12\x0e\n\x06\x66loats\x18\x07 \x03(\x02\x12\x0c\n\x04ints\x18\x08 \x03(\x03\x12\x0f\n\x07strings\x18\t \x03(\x0c\x12/\n\x07tensors\x18\n \x03(\x0b\x32\x1e.aihwx.inferencing.TensorProto\x12\r\n\x05\x62ools\x18\x66 \x03(\x08"\x8f\x01\n\rAttributeType\x12\r\n\tUNDEFINED\x10\x00\x12\t\n\x05\x46LOAT\x10\x01\x12\x07\n\x03INT\x10\x02\x12\n\n\x06STRING\x10\x03\x12\n\n\x06TENSOR\x10\x04\x12\x08\n\x04\x42OOL\x10\x65\x12\n\n\x06\x46LOATS\x10\x06\x12\x08\n\x04INTS\x10\x07\x12\x0b\n\x07STRINGS\x10\x08\x12\x0b\n\x07TENSORS\x10\t\x12\t\n\x05\x42OOLS\x10\x66"\x89\x02\n\x0bTensorProto\x12\x0c\n\x04\x64ims\x18\x01 \x03(\x03\x12\x11\n\tdata_type\x18\x02 \x01(\x05\x12\x16\n\nfloat_data\x18\x04 \x03(\x02\x42\x02\x10\x01\x12\x16\n\nint32_data\x18\x05 \x03(\x05\x42\x02\x10\x01\x12\x13\n\x0bstring_data\x18\x06 \x03(\x0c\x12\x16\n\nint64_data\x18\x07 \x03(\x03\x42\x02\x10\x01"|\n\x08\x44\x61taType\x12\r\n\tUNDEFINED\x10\x00\x12\t\n\x05\x46LOAT\x10\x01\x12\t\n\x05UINT8\x10\x02\x12\x08\n\x04INT8\x10\x03\x12\n\n\x06UINT16\x10\x04\x12\t\n\x05INT16\x10\x05\x12\t\n\x05INT32\x10\x06\x12\t\n\x05INT64\x10\x07\x12\n\n\x06STRING\x10\x08\x12\x08\n\x04\x42OOL\x10\t"\xa2\x01\n\x10TensorShapeProto\x12:\n\x03\x64im\x18\x01 \x03(\x0b\x32-.aihwx.inferencing.TensorShapeProto.Dimension\x1aR\n\tDimension\x12\x13\n\tdim_value\x18\x01 \x01(\x03H\x00\x12\x13\n\tdim_param\x18\x02 \x01(\tH\x00\x12\x12\n\ndenotation\x18\x03 \x01(\tB\x07\n\x05value'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "i_onnx_common_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _TENSORPROTO.fields_by_name["float_data"]._options = None
    _TENSORPROTO.fields_by_name["float_data"]._serialized_options = b"\020\001"
    _TENSORPROTO.fields_by_name["int32_data"]._options = None
    _TENSORPROTO.fields_by_name["int32_data"]._serialized_options = b"\020\001"
    _TENSORPROTO.fields_by_name["int64_data"]._options = None
    _TENSORPROTO.fields_by_name["int64_data"]._serialized_options = b"\020\001"
    _ATTRIBUTEPROTO._serialized_start = 43
    _ATTRIBUTEPROTO._serialized_end = 480
    _ATTRIBUTEPROTO_ATTRIBUTETYPE._serialized_start = 337
    _ATTRIBUTEPROTO_ATTRIBUTETYPE._serialized_end = 480
    _TENSORPROTO._serialized_start = 483
    _TENSORPROTO._serialized_end = 748
    _TENSORPROTO_DATATYPE._serialized_start = 624
    _TENSORPROTO_DATATYPE._serialized_end = 748
    _TENSORSHAPEPROTO._serialized_start = 751
    _TENSORSHAPEPROTO._serialized_end = 913
    _TENSORSHAPEPROTO_DIMENSION._serialized_start = 831
    _TENSORSHAPEPROTO_DIMENSION._serialized_end = 913
# @@protoc_insertion_point(module_scope)
