name: release-build

on:
  workflow_dispatch:

env:
  IBM_CLOUD_REGION: ${{ secrets.IBM_CLOUD_REGION }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_RESOURCE_GROUP: ${{ secrets.IBM_CLOUD_RESOURCE_GROUP }}
  COS_BUCKET: ${{ secrets.COS_BUCKET }}

jobs:
  # ────────────────────────────
  # Stage: Build & Deploy Wheels
  # ────────────────────────────
  build-and-deploy-linux:
    name: Build & Deploy wheels (manylinux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Cleanup runner
        run: |
          pip cache purge
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.8.1
        env:
          CIBW_ENVIRONMENT: "TORCH_VERSION_SPECIFIER='==2.3.1' MAKEFLAGS='-j4'"
          CIBW_BEFORE_BUILD: "pip install torch==2.3.1 torchvision -f https://download.pytorch.org/whl/torch_stable.html && pip install -r requirements.txt"
          CIBW_MANYLINUX_X86_64_IMAGE: "aihwkit/manylinux2014_x86_64_aihwkit"
          CIBW_REPAIR_WHEEL_COMMAND: "auditwheel repair -w {dest_dir} {wheel} --exclude libtorch_python.so"
          CIBW_BUILD: "cp38-manylinux_x86_64 cp39-manylinux_x86_64 cp310-manylinux_x86_64"
        with:
          output-dir: wheelhouse

      - name: Sync wheels to IBM COS
        env:
          IBM_CLOUD_REGION: ${{ secrets.IBM_CLOUD_REGION }}
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
          IBM_CLOUD_RESOURCE_GROUP: ${{ secrets.IBM_CLOUD_RESOURCE_GROUP }}
          COS_BUCKET: ${{ secrets.COS_BUCKET }}
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud plugin install cos
          ibmcloud login --apikey "$IBM_CLOUD_API_KEY" -r "$IBM_CLOUD_REGION" -g "$IBM_CLOUD_RESOURCE_GROUP"
          find "wheelhouse" -type f | while read filepath; do
            relpath="${filepath#wheelhouse/}"
            dest="$relpath"
            echo "Uploading $filepath to $dest"
            ibmcloud cos upload \
              --bucket "$COS_BUCKET" \
              --key "$dest" \
              --file "$filepath" \
              --region "$IBM_CLOUD_REGION"
          done

      - name: Cleanup runner
        if: always()
        run: |
          pip cache purge
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/* /var/cache/apt/*
          rm -rf wheelhouse build dist *.egg-info

  build-and-deploy-macos:
    name: Build & Deploy wheels (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Set up Environment
        run: |
          brew install openblas
          brew link --force openblas
          git clone -b aihwkit https://github.com/aihwkit-bot/delocate.git

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.8.1
        env:
          CIBW_ENVIRONMENT: "TORCH_VERSION_SPECIFIER='==2.3.1'"
          CIBW_BEFORE_BUILD: "pip install torch==2.3.1 torchvision -f https://download.pytorch.org/whl/torch_stable.html && pip install ./delocate && pip install -r requirements.txt"
          CIBW_ARCHS: "x86_64"
          CIBW_BUILD: "cp38-macosx_x86_64 cp39-macosx_x86_64 cp310-macosx_x86_64"
          MACOSX_DEPLOYMENT_TARGET: "10.13"
        with:
          output-dir: wheelhouse

      - name: Sync wheels to IBM COS
        env:
          IBM_CLOUD_REGION: ${{ secrets.IBM_CLOUD_REGION }}
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
          IBM_CLOUD_RESOURCE_GROUP: ${{ secrets.IBM_CLOUD_RESOURCE_GROUP }}
          COS_BUCKET: ${{ secrets.COS_BUCKET }}
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/osx | sh
          ibmcloud plugin install cos
          ibmcloud login --apikey "$IBM_CLOUD_API_KEY" -r "$IBM_CLOUD_REGION" -g "$IBM_CLOUD_RESOURCE_GROUP"
          find "wheelhouse" -type f | while read filepath; do
            relpath="${filepath#wheelhouse/}"
            dest="$relpath"
            echo "Uploading $filepath to $dest"
            ibmcloud cos upload \
              --bucket "$COS_BUCKET" \
              --key "$dest" \
              --file "$filepath" \
              --region "$IBM_CLOUD_REGION"
          done
      - name: Cleanup runner
        if: always()
        run: |
          pip cache purge
          brew cleanup --prune=all
          rm -rf ~/Library/Caches/Homebrew/*
          rm -rf wheelhouse build dist *.egg-info
